plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpIgnorePatterns:
  - ./presets/__tests__/generated/**

yarnPath: .yarn/releases/yarn-berry.cjs
